export const API_KEY = 'bd5abc41888d915c55f8371be137cc49';

export const CITIES_LIST = [
  {name: 'London', country: 'GB'},
  {name: 'Tel Aviv', country: 'IL'},
  {name: 'New York', country: 'US'},
  {name: 'Tokyo', country: 'JP'},
  {name: 'Beijing', country: 'CN'},
  {name: 'Paris', country: 'FR'},
  {name: 'Amsterdam', country: 'NL'},
  {name: 'Copenhagen', country: 'DK'},
  {name: 'Sydney', country: 'AU'},
  {name: 'Bangkok', country: 'TH'},
  {name: 'Nairobi', country: 'KE'},
  {name: 'Jerusalem', country: 'IL'},
  {name: 'Haifa', country: 'IL'},
  {name: 'Mexico City', country: 'MX'},
  {name: 'Rio de Janeiro', country: 'BR'},
  {name: 'Buenos Aires', country: 'AR'},
  {name: 'Santiago', country: 'CL'},
  {name: 'Manchester', country: 'GB'},
  {name: 'Cairo', country: 'EG'},
  {name: 'Johannesburg', country: 'ZA'},
  {name: 'Istanbul', country: 'TR'},
  {name: 'Delhi', country: 'IN'},
  {name: 'Mumbai', country: 'IN'},
  {name: 'Seoul', country: 'KR'},
  {name: 'Shanghai', country: 'CN'},
  {name: 'Moscow', country: 'RU'},
];
